U21557277_HW03/Models/FileModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.IO;
using System.ComponentModel.DataAnnotations;
using System.Web;

namespace U21557277_HW03.Models
{
    public class FileModel
    {
        //Display options.

        [Display(Name = "File Name")]
        public string FileName { get; set; }

        [Required(ErrorMessage = "Please select file.")]
        [Display(Name = "Browse File")]
        public HttpPostedFileBase[] Files { get; set; }

        public string file { get; set; }
    }
}

U21557277_HW03/Controllers/AboutMeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace U21557277_HW03.Controllers
{
    public class AboutMeController : Controller
    {
        // GET: AboutMe
        public ActionResult Index()
        {
            return View();
        }
    }
}

U21557277_HW03/Controllers/FilesController.cs
using U21557277_HW03.Models;
using System.Collections.Generic;

using System.IO;
using System.Web.Mvc;

namespace U21557277_HW03.Controllers
{
    public class FilesController : Controller
    {
        public ActionResult Index()
        {
            

            string[] filePaths = Directory.GetFiles(Server.MapPath("~/App_Data/Media/Documents/"));

           

            List<FileModel> files = new List<FileModel>();

            foreach (string filePath in filePaths)
            {
                files.Add(new FileModel { FileName = Path.GetFileName(filePath) });
            }
            return View(files);
        }

        public FileResult DownloadFile(string fileName) 
        {
          

            string path = Server.MapPath("~/App_Data/Media/Documents/") + fileName;

           

            byte[] bytes = System.IO.File.ReadAllBytes(path);

           

            return File(bytes, "application/octet-stream", fileName);
        }

        public ActionResult DeleteFile(string fileName)
        {

            string path = Server.MapPath("~/App_Data/Media/Documents/") + fileName;
            byte[] bytes = System.IO.File.ReadAllBytes(path);

            System.IO.File.Delete(path);

            return RedirectToAction("Index");
        }

    }
}

U21557277_HW03/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.IO;
using System.Web;
using System.Web.Mvc;

namespace U21557277_HW03.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(HttpPostedFileBase[] Files)
        {
           
            if (ModelState.IsValid)
            {  
                foreach (HttpPostedFileBase file in Files)
                {
                    
                    if (file != null)
                    {
                        var InputFileName = Path.GetFileName(file.FileName);
                        var ServerSavePath = Path.Combine(Server.MapPath("~/App_Data/Media/Documents/") + InputFileName);
                        
                        file.SaveAs(ServerSavePath);
                    }
                }
            }
            return View();
        }
    }
}

U21557277_HW03/Controllers/ImagesController.cs
using System;
using U21557277_HW03.Models;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.IO;
using System.Web.Mvc;

namespace U21557277_HW03.Controllers
{
    public class ImagesController : Controller
    {
        // GET: Images
        public ActionResult Index()
        {
           

            string[] filePaths = System.IO.Directory.GetFiles(Server.MapPath("~/App_Data/Media/Images/"));

            
            List<FileModel> files = new List<FileModel>();

            foreach (string filePath in filePaths)
            {
                files.Add(new FileModel { FileName = Path.GetFileName(filePath) });
            }
            return View(files);
        }

        public FileResult DownloadFile(string fileName) 
        {
            

            string path = Server.MapPath("~/App_Data/Media/Images/") + fileName;

           

            byte[] bytes = System.IO.File.ReadAllBytes(path);

            

            return File(bytes, "application/octet-stream", fileName);
        }

        public ActionResult DeleteFile(string fileName)
        {
            
            string path = Server.MapPath("~/App_Data/Media/Images/") + fileName;
            byte[] bytes = System.IO.File.ReadAllBytes(path);

            System.IO.File.Delete(path);

            return RedirectToAction("Index");
        }

    }
}

U21557277_HW03/Controllers/VideosController.cs
using System;
using U21557277_HW03.Models;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace U21557277_HW03.Controllers
{
    public class VideosController : Controller
    {
        // GET: Videos
        public ActionResult Index()
        {
          

            string[] filePaths = Directory.GetFiles(Server.MapPath("~/App_Data/Media/Videos/"));

           

            List<FileModel> files = new List<FileModel>();

            foreach (string filePath in filePaths)
            {
                files.Add(new FileModel { FileName = Path.GetFileName(filePath) });
            }
            return View(files);
        }

        public FileResult DownloadFile(string fileName) 
        {
           

            string path = Server.MapPath("~/App_Data/Media/Videos/") + fileName;

           

            byte[] bytes = System.IO.File.ReadAllBytes(path);

           
            return File(bytes, "application/octet-stream", fileName);
        }

        public ActionResult DeleteFile(string fileName)
        {
            

            string path = Server.MapPath("~/App_Data/Media/Videos/") + fileName;
            byte[] bytes = System.IO.File.ReadAllBytes(path);

            System.IO.File.Delete(path);

            return RedirectToAction("Index");
        }

    }
}

U21557277_HW03/Views/AboutMe/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<table>
    <tr>
        <td>
            <div style=" padding-bottom: 60px;">
                <h2>About Me</h2>

                <h4>All about Martha Aphane</h4>

                <div class="card" style=" padding-bottom:50px; text-align:left; width: 850px; height: 180px; border: 0.5px solid #000000; background: #E1AD9D;
                overflow: visible;">
                    <p style="margin-left:1%; margin-top:1%;">
                        <h4>Bio</h4>

                        Martha, is a 21 year-old young lady who was born and raised in a small township
                        just outside Pretoria called Hammanskraal. She is currently a second year Bcom
                        Informatics Information Systems. From a young age, Martha has always had an
                        interest in computers and how they operate and in high school she fell in love with
                        Business studies subject. Therefore, Informatics was the best course for her since it
                        has commerce and computer modules combined.

                        In future Martha wants to be a Business Analyst. She is very shy, yet enjoys working with
                        people. Martha is kind-hearted and loves helping people.
                    </p>
                 <br />

        </div>
        </div>

        </td>
        <td>   </td>
        <td></td>
        <td>
            <div style="margin-left: 8%;">
                <img src="@Url.Content("~/App_Data/Media/Images/@file.FileName")" alt="Bio Image" style="border-radius:20px; border-style:solid; border:5px; width:200px;
                     height:180px; margin-left:auto; margin-right:auto; object-fit:fill; margin-top:3px; padding-top:7%; padding-bottom: 7%;">
            </div>
        </td>

    </tr>
</table>

U21557277_HW03/Views/Files/Index.cshtml
@using U21557277_HW03.Models
@model List<FileModel>


@{
    ViewBag.Title = "Downloader";
}
<head>
    <style type="text/css">
        .auto-style {
            color: #FFFFFF;
        }

        .t {
            text-align: center;
            vertical-align: middle;
        }
    </style>
</head>
<div class="well-sm">
    <h2>File Download / Delete</h2>

</div>


<div style="height: 400px; overflow: auto;">
    <div>
        <table class="table table-condensed table-hover">
            <thead style="position: sticky;top: 0">
                <tr bgcolor="#222222" class="auto-style">
                    <th class="col-lg-8">File Name</th>
                    <th class="t, col-lg-2">DOWNLOAD</th>
                    <th class="t, col-lg-2">DELETE</th>
                </tr>
            </thead>
            @foreach (FileModel file in Model)
            {
                <tr>
                    
                        Default >> @Html.DisplayFor(modelItem => file.FileName)
                    

                    <td>@file.FileName</td>
                    <td>
                        <button style="background-color:springgreen;">
                            @Html.ActionLink("Download", "DownloadFile",
                             new { fileName = file.FileName })
                        </button>
                    </td>
                    <td>
                        <button style="background-color:red">
                            @Html.ActionLink("DELETE", "DeleteFile",
                           new { fileName = file.FileName },
                           new { onclick = "return confirm('Are you sure you want to delete this?');" })
                        </button>
                    </td>
                </tr>
            }
        </table>
    </div>
</div>

U21557277_HW03/Views/Home/Index.cshtml
@model U21557277_HW03.Models.FileModel
@{
    ViewBag.Title = "Index";
}
<table>
    <tr>
        <td>
            <div style=" padding-bottom: 60px;">
                <h2>INF 272 Media</h2>

                <h4>All about INF 272 assessments</h4>

                <div class="card" style=" padding-bottom:50px; text-align:left; width: 850px; height: 180px; border: 0.5px solid #000000; background: #E1AD9D;
             overflow: visible; ">
                    <p style="margin-left:1%; margin-top:1%;">
                        <h3>Description</h3>
                        This page will help you save all your important documents for INF 272. You can upload documents, images and videos that you have used to keep
                        them safe for later use.This will be very useful as you can always use the material you upload to refer later on in the year.
                        <br />
                        How it works is: You select the type of file you wish to upload (pdf, image or video), then you click on the submit button, your file will
                        be uploaded. You can then download or delete a file if you wish do so from the list of files you have uploaded.
                    </p>
                </div>
            </div>
        </td>
        <td>   </td>
        <td>


            <div style="align-content:start; margin-left: 6.5%;">

                <h2>Option Selection</h2>

                <div>
                    <form id="form1" method="post">

                        <table>
                            <tr class="form-horizontal">

                                
                                @using (Html.BeginForm("Index", "Home", FormMethod.Post))
                                {

                                    <span>Documents </span>
                                    @Html.RadioButton("FileType", "Documents", true)
                                    <br />
                                    <span>Images </span>
                                    @Html.RadioButton("FileType", "Images", false)
                                    <br />
                                    <span>Videos </span>
                                    @Html.RadioButton("FileType", "Videos", false)


                                }

                            </tr>
                        </table>

                        <br />

                        <div style="margin-left:2%">
                            @using (Html.BeginForm("Index", "Files", FormMethod.Post, new { enctype = "multipart/form-data" }))
                            {
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                <div>@Html.TextBoxFor(model => model.Files, "", new { @type = "file", @multiple = "multiple" })</div>
                                <br />
                                <div><input type="submit" value="Submit" /></div>

                            }

                        </div>


                    </form>
                </div>
            </div>
        </td>
    </tr>
</table>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

U21557277_HW03/Views/Images/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Images</h2>

<h4>All the uploaded images which ca be found under "App_data/Media/Images folder</h4>



@*@using (Html.BeginForm("Index", "Images", FormMethod.Post, new { enctype = "multipart/form-data" }))
{*@
    

@*<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.file, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.file, new { htmlAttributes = new { @class = "form-control", @type = "file" } })
            @Html.ValidationMessageFor(model => model.file, "", new { @class = "text-danger" })
        </div>
    </div>

    <div>*@
        @*@foreach (FileMode file in Model)

        {
            @Html.DisplayFor(modelItem => file.fileName)
            <div>@file.fileName</div>
            <button style="background-color:springgreen;">
                @Html.ActionLink("Download", "DownloadFile",
                 new { fileName = file.fileName })
            </button>
            <button style="background-color:red">
                @Html.ActionLink("DELETE", "DeleteFile",
               new { fileName = file.fileName },
               new { onclick = "return confirm('Are you sure you want to delete this?');" })
            </button>
        </div>*@
          @*}*@
@*</div>*@

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
 

U21557277_HW03/Views/Shared/_Layout.cshtml
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - File Data</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
    <link rel="stylesheet" href="~/Content/Site.css">
</head>
<body>

    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("HOME", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Files", "Index", "Files")</li>
                    <li>@Html.ActionLink("Images", "Index", "Images")</li>
                    <li>@Html.ActionLink("Videos", "Index", "Videos")</li>
                    <li>@Html.ActionLink("AboutMe", "Index", "AboutMe")</li>
                </ul>
            </div>
        </div>
    </div>



    <div class="container body-content">
        <div class="well-sm">
            <p>

            </p>
            <hr />
        </div>



        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - INF 272 Homework 03</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

U21557277_HW03/Views/Videos/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Videos</h2>

<h4>All uploaded videos can be deleted or downloaded on this page</h4>

@*@foreach (FileMode file in Model)

    {
        @Html.DisplayFor(modelItem => file.fileName)
        <div>@file.fileName</div>
        <button style="background-color:springgreen;">
            @Html.ActionLink("Download", "DownloadFile",
             new { fileName = file.fileName })
        </button>
        <button style="background-color:red">
            @Html.ActionLink("DELETE", "DeleteFile",
           new { fileName = file.fileName },
           new { onclick = "return confirm('Are you sure you want to delete this?');" })
        </button>
    </div>*@

 